### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by hardikchopra242** [IoT-Buzz/IoT#18]
Update README in [Hardware](https://github.com/IoT-Buzz/IoT/tree/main/Hardware) directory.

**Comment by Pranjalmishra30** [comment]
Hey i would like to work on this issue. Could you assign this to me 
Thanks :+1:

**Comment by hardikchopra242** [comment]
Hey! 
Don't forget to make a table of contents with a brief intro. Make the first heading centered and subHeadings left-aligned.
