### ISSUE TITLE
Update Readme in Projects

### ISSUE THREAD

**Issue by hardikchopra242** [IoT-Buzz/IoT#20]
Update Readme in [Projects](https://github.com/IoT-Buzz/IoT/tree/main/projects) directory.

**Comment by Pranjalmishra30** [comment]
Hey i would like to work on this issue.

**Comment by singhaditya28** [comment]
hey, I'd like to work on this.

**Comment by naazkakria** [comment]
@singhaditya28  yeah please work on it, and go through https://github.com/IoT-Buzz/IoT/blob/main/README.md  , and try to maintain it in a similar template

**Comment by singhaditya28** [comment]
@naazkakria Have solved it can you please review the PR & merge it and add the accepted label?
