### ISSUE TITLE
Basic Email Client (python script)

### ISSUE THREAD

**Issue by naazkakria** [IoT-Buzz/IoT#38]

**Comment by 26tanishabanik** [comment]
@naazkakria  I would like to take up this issue

**Comment by nayan2306** [comment]
@naazkakria I want to work on this issue please assign me the work

**Comment by 26tanishabanik** [comment]
> @naazkakria I would like to take up this issue

@naazkakria The script is ready for basic email client in python, can I make a pull request?

**Comment by naazkakria** [comment]
@26tanishabanik  I want a custom email sender if you can work on that i will create a new issue , this issue was assigned to someone else

**Comment by naazkakria** [comment]
@nayan2306  issue was assigned to someone else, I will update some more issues tomorrow

**Comment by 26tanishabanik** [comment]
> @26tanishabanik I want a custom email sender if you can work on that i will create a new issue , this issue was assigned to someone else

Yes sure, can you elaborate the feature a bit more in detail, it will be helpful for me

**Comment by naazkakria** [comment]
@26tanishabanik ," Sending Multiple Personalized Emails" will create this  issue tomorrow
